export const TEXT_DATA_TEXT_TO_INPUT_FETCHED = 'TEXT_DATA_TEXT_TO_INPUT_FETCHED';
export const TEXT_DATA_CORRECT_SYMBOL_ADDED = 'TEXT_DATA_CORRECT_SYMBOL_ADDED';
export const TEXT_DATA_INCORRECT_SYMBOL_ADDED = 'TEXT_DATA_INCORRECT_SYMBOL_ADDED';
export const TEXT_DATA_RESET = 'TEXT_DATA_RESET';